ActiveSupport::Inflector.inflections do |inflect|
  inflect.acronym 'AML'
  inflect.acronym 'API'
  inflect.acronym 'AMQP'
  inflect.acronym 'MQ'
  inflect.acronym 'CORS'
  inflect.acronym 'UI'
  inflect.acronym 'UUID'
  inflect.acronym 'P2P'
  inflect.acronym 'CRUD'
  inflect.acronym 'KYC'
  inflect.acronym 'TID'
  inflect.acronym 'OWHDWallet'
  inflect.irregular 'cash', 'cash'
end